language: java

jdk:
  - oraclejdk8
  
before_script:
  - echo $TRAVIS_BUILD_DIR
  - cd $TRAVIS_BUILD_DIR/java/impl/src/test/resources/testdata/localmavenproject/maven.project
  - mvn install
  - cd $TRAVIS_BUILD_DIR

script: mvn install

sudo: false

cache:
  directories:
    - $HOME/.m2

branches:
  except:
    - gh-pages

notifications:
  email:
    - joerg.hohwiller@googlemail.com
